# Generated by Django 3.0.6 on 2020-05-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpatient',
            old_name='date',
            new_name='create_date',
        ),
    ]
