# Generated by Django 3.0.6 on 2020-05-24 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
